console.log(1 + true)
console.log(1 + false)
console.log ("25" + 5)
console.log(5 + "25")
console.log(+"25" + "5")
console.log("undefined " + undefined)
console.log(25 * "")
console.log({} ? "true" : "false")
console.log(" 25"+ 5)
console.log(+" 25"+ 5)
console.log(5+ " 25")
console.log(+" 25")
console.log(Number(" 25 "))
console.log (" 3" == 3)
console.log(" 3" + 3)
console.log(Number(" 3") + 3)
console.log(12.2545.toFixed(2))
console.log(12.2545.toExponential(5))

